# Generated by Django 4.2.1 on 2023-05-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='weights',
            field=models.FileField(blank=True, null=True, upload_to='media/weights'),
        ),
    ]
