# Generated by Django 4.2.1 on 2023-05-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_run_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='user_profile_pictures'),
        ),
        migrations.AlterField(
            model_name='run',
            name='weights',
            field=models.FileField(blank=True, null=True, upload_to='weights'),
        ),
    ]
