# Generated by Django 4.2.1 on 2023-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_myuser_image_alter_run_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='network',
            field=models.FileField(blank=True, null=True, upload_to='network'),
        ),
    ]
