# Generated by Django 4.2.1 on 2023-06-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_run_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
