# Generated by Django 4.2.1 on 2023-08-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='problem_objective',
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
