# Generated by Django 4.2.1 on 2023-08-11 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_project_problem_objective_project_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('latest_run_index', models.DecimalField(decimal_places=0, default=0, max_digits=6, null=True)),
                ('outline_key', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='objective',
        ),
    ]
