# Generated by Django 4.2.1 on 2023-08-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_project_latest_sweep_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sweep',
        ),
        migrations.RemoveField(
            model_name='project',
            name='latest_sweep_index',
        ),
    ]
