# Generated by Django 4.2.1 on 2023-09-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_project_latest_dataset_run_nodename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metadata',
        ),
    ]
