# Generated by Django 4.2.1 on 2023-09-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='directory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
