# Generated by Django 4.2.1 on 2023-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_project_latest_dataset_run_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_caption',
            field=models.TextField(blank=True, default='Add caption', null=True),
        ),
    ]
