# Generated by Django 4.2.1 on 2023-11-06 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_images_image_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_path', models.TextField(blank=True, null=True)),
                ('metric_name', models.TextField(blank=True, null=True)),
                ('metric_value', models.TextField(blank=True, null=True)),
                ('track', models.TextField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.run')),
            ],
        ),
    ]
