# Generated by Django 4.2.1 on 2023-11-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='track',
            new_name='track_dict',
        ),
        migrations.AddField(
            model_name='model',
            name='library',
            field=models.TextField(blank=True, null=True),
        ),
    ]
