# Generated by Django 4.2.1 on 2023-11-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_track_model_track_dict_model_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
